services:
    telegram.command.register.startstep:
        alias: App\Command\Register\StartStep
        public: true:

    telegram.command.register.subjectstep:
        alias: App\Command\Register\SubjectStep
        public: true
