services:
    telegram.command.register:
        alias: App\Service\Command\Register\v1
        public: true

    #App\Service\Command\Register\v1:
    #    arguments:
    #        $sendMessageFactory: '@telegram.model.methods.send.message.factory'
    #        $responseFactory: '@model.command.response.factory'
    #        $replyKeyboardMarkupFactory: '@telegram.model.type.replykeyboardmarkup.factory'
    #        $keyboardButtonFactory: '@telegram.model.type.replymarkup.keyboardbutton.factory'
