services:
    telegram.command.start:
        alias: App\Service\Command\Start\Start_v1
        public: true

    App\Service\Command\Start\Start_v1:
        arguments:
            $sendMessageFactory: '@telegram.model.send.message.factory'
            $responseFactory: '@model.command.response.factory'

